# Generated by Django 4.2.10 on 2024-03-06 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.CharField(max_length=50)),
                ('customer_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('zipcode', models.CharField(max_length=20)),
                ('description', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=50)),
                ('mark', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Product_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=50)),
                ('mark', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_name', models.CharField(max_length=50)),
                ('partner_name', models.CharField(max_length=50)),
                ('hours_worked1_partner_user', models.DecimalField(decimal_places=6, default=0, max_digits=50)),
                ('hours_worked_main_user', models.IntegerField()),
                ('number_of_spots', models.DecimalField(decimal_places=6, default=0, max_digits=50)),
                ('number_of_boitier', models.DecimalField(decimal_places=6, default=0, max_digits=50)),
                ('raccordement', models.DecimalField(decimal_places=6, default=0, max_digits=50)),
                ('description', models.TextField(default='N/A', max_length=500)),
                ('observation', models.TextField(default='N/A', max_length=500)),
            ],
        ),
    ]
