# Generated by Django 4.2.10 on 2024-03-05 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_customer_product_rename_city_report_partner_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='hours_worked_main_user',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=50),
        ),
    ]
