# Generated by Django 4.2.10 on 2024-03-06 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_report_hours_worked_main_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='hours_worked_main_user',
            field=models.IntegerField(),
        ),
    ]
